name: Release
on: workflow_dispatch

permissions:
  contents: write
  discussions: write

env:
  env:
  PROJECT_NAME: DELTARUNE
  REPO_PATH: Ethantobot11/DELTASHIT

jobs:
  get-commit-hash:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get_commit_hash.outputs.COMMIT_HASH }}
    steps:
      - name: Check Repository
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "REPO_PATH: ${{ env.REPO_PATH }}"
          if [[ "$GITHUB_REPOSITORY" != "${{ env.REPO_PATH }}" ]]; then
            echo "Doesn't seem to be correct, returning SIGABRT..."
            exit 6
          else
            echo "Seems to be correct..."
          fi

      - name: Get latest commit hash
        id: get_commit_hash
        run: |
          commit_hash=${GITHUB_SHA::7}
          echo "Latest commit hash is $commit_hash"
          echo "::set-output name=COMMIT_HASH::$commit_hash"
          :
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Windows x64
            os: windows-2022
            buildArgs: "windows -final -X64 -D HXCPP_X64 -D 64bits"
            artifactName: Windows x64
            artifactPath: export/64bits/release/windows/bin/
          - name: Windows x32
            os: windows-2022
            buildArgs: "windows -final -X32 -D HXCPP_X32 -D 32bits"
            artifactName: Windows x32
            artifactPath: export/32bits/release/windows/bin/
          - name: Linux
            os: ubuntu-22.04
            buildArgs: "linux -final"
            artifactName: Linux
            artifactPath: export/release/linux/bin/
          - name: MacOS
            os: macos-15
            buildArgs: "mac -final"
            artifactName: MacOS
            artifactPath: export/release/macos/bin/
          - name: Android
            os: macos-15
            buildArgs: "android -final -D officialBuild -nocompile-pch"
            artifactName: Android
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: iOS
            os: macos-15
            buildArgs: "ios -final -nosign"
            artifactName: iOS
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
          - name: HTM5
            os: windows-latest
            buildArgs: "html5 -final"
            artifactName: HTML5
            artifactPath: "export/release/html5/*"
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}

  Releaser:
    needs: [get-commit-hash,build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Windows x64 Build
        uses: actions/download-artifact@main
        with:
          name: Windows x64
          path: /home/runner/Windows-x64

      - name: Zip Windows x64 Build For Release
        run: |
          cd /home/runner/Windows-x64
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Windows-x64.zip" .

      - name: Download Windows x32 Build
        uses: actions/download-artifact@main
        with:
          name: Windows x32
          path: /home/runner/Windows-x32

      - name: Zip Windows x32 Build For Release
        run: |
          cd /home/runner/Windows-x32
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Windows-x32.zip" .

      - name: Download Linux Build
        uses: actions/download-artifact@main
        with:
          name: Linux
          path: /home/runner/Linux

      - name: Tar Linux Build For Release
        run: |
          cd /home/runner/Linux
          tar czf "/home/runner/${{ env.PROJECT_NAME }}-Linux.tar" .

      - name: Download MacOS Build
        uses: actions/download-artifact@main
        with:
          name: MacOS
          path: /home/runner/MacOS

      - name: Tar MacOS Build For Release
        run: |
          cd /home/runner/MacOS
          tar czf "/home/runner/${{ env.PROJECT_NAME }}-MacOS.tar" .

      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
          name: Android
          path: /home/runner

      - name: Move Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/${{ env.PROJECT_NAME }}-Android.apk

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
          name: iOS
          path: ${{ github.workspace }}

      - name: Move iOS File
        run: mv ${{ github.workspace }}/${{ env.PROJECT_NAME }}.ipa /home/runner/${{ env.PROJECT_NAME }}-iOS.ipa

      - name: Download HTM5 Build
        uses: actions/download-artifact@main
        with:
          name: HTML5
          path: /home/runner/html5

      - name: Zip HTML5 Build For Release
        run: |
          cd /home/runner/html5
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-HTML5.zip" .

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "DevBuild ${{ needs.get-commit-hash.outputs.commit_hash }}"
          tag_name: "devbuild-${{ needs.get-commit-hash.outputs.commit_hash }}"
          make_latest: false
          files: |
            /home/runner/*.apk
            /home/runner/*.ipa
            /home/runner/*.tar
            /home/runner/*.zip
